import type { Metadata } from "next";
import {
  Fira_Mono,
  IBM_Plex_Mono,
  IBM_Plex_Sans,
  Inconsolata,
  Inter,
  Manrope,
} from "next/font/google";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "../lib/utils";
import { Providers } from "./providers";

const firaMono = Fira_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-fira-mono",
});

const inconsolata = Inconsolata({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-inconsolata",
});

const manrope = Manrope({
  weight: ["500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        firaMono.variable,
        GeistMono.variable,
        GeistSans.variable,
        inconsolata.variable,
        manrope.variable,
        inter.variable,
        ibmPlexSans.variable,
        ibmPlexMono.variable
      )}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
